### ISSUE TITLE
Add Makefile

### ISSUE THREAD

**Issue by cdeil** [GooFit/GooTorial#2]
I tried adding a Makefile to compile the examples and exercises by setting a shell environment variable

```
export GOOFIT=/Users/deil/code/GooFit
```

and then building like this:

```
example2:
    nvcc -m64 -arch=sm_20 -o example2 example2.cu -I$(GOOFIT) -L$(GOOFIT)/rootstuff -lRootUtils
```

This does compile, but when I try to execute `example2` it can't find the `RootUtils` library:

```
$ ./example2 
dyld: Library not loaded: libRootUtils.so
  Referenced from: /Users/deil/code/GooTorial/./example2
  Reason: image not found
Trace/BPT trap: 5
$ otool -L example2
example2:
    libRootUtils.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libcudart.dylib (compatibility version 1.1.0, current version 5.0.0)
    /opt/local/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.17.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 169.3.0)
    /opt/local/lib/gcc47/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

@RolfAndreassen Do you know how to write the Makefile?

(Once there is a Makefile, `compexp3` and `compexp4` should be removed.)

**Comment by ktomko** [comment]
Try setting the LD_LIBRARY_PATH environment variable (assuming a Linux install) prior to running the example code.
     export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$GOOFIT/rootstuff
- Karen

**Comment by cdeil** [comment]
Thanks @ktomko ... this works:

```
export GOOFIT=/Users/deil/code/GooFit
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$GOOFIT/rootstuff
```

and in the Makefile

```
INCLUDES += -I$(GOOFIT) -I$(GOOFIT)/FPOINTER -I$(GOOFIT)/rootstuff -I$(ROOTSYS)/include/

examples: example2 example3a example3b example3c example4a example4b example4c example4d example4e

example2:
    nvcc -m64 -arch=sm_20 -o example2 example2.cu $(INCLUDES) -L$(GOOFIT)/rootstuff -lRootUtils

example3a:
    nvcc -m64 -arch=sm_20 -o example3a example3a.cu $(INCLUDES) -L$(GOOFIT)/rootstuff -lRootUtils
```

I'm very bad at Makefiles, e.g. I don't know how to write a rule that will work for all examples and avoids the repetition, so I'd prefer if someone else writes this. (For the later examples `-l` flags are still missing)

**Comment by RolfAndreassen** [comment]
Ok, I wrote a Makefile for the examples and exercises.
